In [1]:
!pip install GitPython
from git import Repo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 181 kB 4.2 MB/s 
     |████████████████████████████████| 63 kB 1.9 MB/s 


In [2]:
access_token = "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"

In [3]:
HTTPS_REMOTE_URL = 'https://' + access_token + ':x-oauth-basic@github.com/Bsingstad/Heart-murmur-detection-2022-private'
DEST_NAME = 'heart_murmurs'
cloned_repo = Repo.clone_from(HTTPS_REMOTE_URL, DEST_NAME)

In [4]:
!pip install wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9675 sha256=bdcf2c05f02c0ce84011441a936e5797a2f6fc88d46e039df7855105df0d5a55
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget


In [5]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json'

kaggle.json
/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file


In [6]:
!kaggle datasets download -d bjoernjostein/the-circor-digiscope-phonocardiogram-dataset-v2

 99% 445M/449M [00:18<00:00, 28.0MB/s]
100% 449M/449M [00:18<00:00, 25.9MB/s]


In [7]:
import os, zipfile
try:
  os.mkdir("/content/data/")
except:
  print("data folder allready exists")

In [8]:
import os, zipfile

dir_name = "/content/"
target_dir = "/content/data/"
extension = ".zip"
 
os.chdir(dir_name) # change directory from working dir to dir with files

for item in os.listdir(dir_name): # loop through items in dir
    if item.endswith(extension): # check for ".zip" extension
        file_name = os.path.abspath(item) # get full path of files
        zip_ref = zipfile.ZipFile(file_name) # create zipfile object
        zip_ref.extractall(target_dir) # extract file to dir
        zip_ref.close() # close file
        os.remove(file_name) # delete zipped file

In [9]:
os.mknod("/content/heart_murmurs/__init__.py")

In [17]:
%load_ext autoreload
%autoreload
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [18]:
from heart_murmurs.helper_code import *

# have to add a "." in from of the module imports (in the scrips:train_model, run_model and team_code )
from heart_murmurs.train_model import *
from heart_murmurs.run_model import *
from heart_murmurs.team_code import *
from heart_murmurs.evaluate_model import *
from heart_murmurs.cross_validate import *

In [12]:
try:
  os.mkdir("/content/models/")
except:
  print("model folder allreadu exists")

In [13]:
try:
  os.mkdir("/content/results/")
except:
  print("results folder allreadu exists")

In [19]:
murmur_probas, outcome_probas, murmur_trues, outcome_trues = cv_challenge_model("/content/data/training_data/training_data/", "/content/results/", 1)

Finding data files...
Extracting features and labels from the Challenge data...


  0%|          | 0/942 [00:00<?, ?it/s]/content/heart_murmurs/cross_validate.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(current_recordings)[indx]
100%|██████████| 942/942 [00:22<00:00, 41.53it/s]


Number of signals = 942
Murmurs prevalence:
Present = 179, Unknown = 68, Absent = 695
Outcomes prevalence:
Abnormal = 456, Normal = 486
Epoch 1/2
43/43 [==============================] - 43s 869ms/step - loss: 1.4481 - murmur_output_loss: 0.7593 - clinical_output_loss: 0.6887 - lr: 0.0010
Epoch 2/2
43/43 [==============================] - 37s 869ms/step - loss: 1.3520 - murmur_output_loss: 0.6833 - clinical_output_loss: 0.6686 - lr: 0.0010
0.7578947368421053
0.5263157894736842
Epoch 1/2
43/43 [==============================] - 42s 869ms/step - loss: 1.4258 - murmur_output_loss: 0.7406 - clinical_output_loss: 0.6852 - lr: 0.0010
Epoch 2/2
43/43 [==============================] - 37s 868ms/step - loss: 1.3301 - murmur_output_loss: 0.6643 - clinical_output_loss: 0.6659 - lr: 0.0010
0.18947368421052632
0.4842105263157895
Epoch 1/2
43/43 [==============================] - 43s 874ms/step - loss: 1.4409 - murmur_output_loss: 0.7542 - clinical_output_loss: 0.6867 - lr: 0.0010
Epoch 2/2
43/43 [

In [20]:
murmur_probas

[array([[1.67414799e-01, 2.43691262e-04, 8.32341492e-01],
        [8.57618570e-01, 3.26999716e-18, 1.42381459e-01],
        [1.68866232e-01, 3.56947328e-03, 8.27564299e-01],
        [1.39360681e-01, 1.16191339e-03, 8.59477401e-01],
        [1.87277913e-01, 3.90463346e-03, 8.08817446e-01],
        [1.36480659e-01, 6.88013533e-05, 8.63450587e-01],
        [1.44978046e-01, 2.26942985e-03, 8.52752566e-01],
        [2.05703169e-01, 7.50419870e-03, 7.86792696e-01],
        [1.49990603e-01, 2.42899545e-03, 8.47580373e-01],
        [2.86967933e-01, 3.20736181e-05, 7.13000059e-01],
        [1.94772094e-01, 3.71526717e-03, 8.01512659e-01],
        [1.80473611e-01, 8.03302217e-04, 8.18723083e-01],
        [1.27257824e-01, 9.69323516e-03, 8.63048971e-01],
        [1.33175284e-01, 4.73580603e-03, 8.62088919e-01],
        [1.30564347e-01, 1.87668751e-03, 8.67558956e-01],
        [1.89196810e-01, 1.37811131e-03, 8.09425056e-01],
        [1.57276928e-01, 6.54912973e-03, 8.36173952e-01],
        [1.690

In [31]:
train_challenge_model("/content/data/training_data/training_data/", "/content/models/", 1)

Finding data files...
Extracting features and labels from the Challenge data...


  0%|          | 0/942 [00:00<?, ?it/s]/content/heart_murmurs/team_code.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(current_recordings)[indx]
100%|██████████| 942/942 [00:22<00:00, 41.31it/s]


Number of signals = 942
Murmurs prevalence:
Present = 179, Unknown = 68, Absent = 695
Outcomes prevalence:
Abnormal = 456, Normal = 486
Epoch 1/25
48/48 [==============================] - 58s 868ms/step - loss: 1.4302 - murmur_output_loss: 0.7464 - clinical_output_loss: 0.6838 - lr: 0.0010
Epoch 2/25
48/48 [==============================] - 42s 866ms/step - loss: 1.3504 - murmur_output_loss: 0.6760 - clinical_output_loss: 0.6743 - lr: 0.0010
Epoch 3/25
48/48 [==============================] - 42s 865ms/step - loss: 1.3324 - murmur_output_loss: 0.6577 - clinical_output_loss: 0.6747 - lr: 0.0010
Epoch 4/25
48/48 [==============================] - 42s 866ms/step - loss: 1.3035 - murmur_output_loss: 0.6458 - clinical_output_loss: 0.6578 - lr: 0.0010
Epoch 5/25
48/48 [==============================] - 42s 866ms/step - loss: 1.2955 - murmur_output_loss: 0.6461 - clinical_output_loss: 0.6494 - lr: 0.0010
Epoch 6/25
48/48 [==============================] - 42s 866ms/step - loss: 1.2819 - murmu

In [33]:
try:
  os.mkdir("/content/output/")
except:
  print("output folder allready exist..")

output folder allready exist..


In [34]:
run_model("/content/models", "/content/data/training_data/training_data/", "/content/output/", allow_failures=True, verbose=1)

Loading Challenge model...
Running model on Challenge data...


/content/heart_murmurs/team_code.py:192: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(recordings)[indx]


Done.


In [37]:
evaluate_model("/content/data/training_data/training_data/", "/content/output/")

((['Present', 'Unknown', 'Absent'],
  0.8556025729938078,
  0.671036783625729,
  array([0.84369989, 0.87146655, 0.85164128]),
  array([0.71209607, 0.37082386, 0.93019042]),
  0.4834474605466972,
  array([0.5648855 , 0.        , 0.88545689]),
  0.8089171974522293,
  array([0.41340782, 0.        , 0.98992806]),
  0.5897435897435898,
  20906.579956748126),
 (['Abnormal', 'Normal'],
  0.26931042884990286,
  0.3702039983065212,
  array([0.26931043, 0.26931043]),
  array([0.36334753, 0.37706047]),
  0.2819400700817226,
  array([0.43668122, 0.12719892]),
  0.31528662420382164,
  array([0.54824561, 0.09670782]),
  0.4689081706435286,
  16227.333768852646))

CV

In [56]:
folds = 10

In [57]:
skf = StratifiedKFold(n_splits=folds)