In [1]:
!pip install GitPython
from git import Repo

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 181 kB 8.4 MB/s 
     |████████████████████████████████| 63 kB 1.0 MB/s 


In [2]:
access_token = "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"

In [3]:
HTTPS_REMOTE_URL = 'https://' + access_token + ':x-oauth-basic@github.com/Bsingstad/Heart-murmur-detection-2022-private'
DEST_NAME = 'heart_murmurs'
cloned_repo = Repo.clone_from(HTTPS_REMOTE_URL, DEST_NAME)

In [4]:
!pip install wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9675 sha256=007a18611711f55a2c3042569edf07ddc3e09d972e56f8ef5d7c3f98c8546eab
  Stored in directory: /root/.cache/pip/wheels/a1/b6/7c/0e63e34eb06634181c63adacca38b79ff8f35c37e3c13e3c02
Successfully built wget


In [7]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json'

kaggle.json
/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file


In [8]:
!kaggle datasets download -d bjoernjostein/the-circor-digiscope-phonocardiogram-dataset-v2

 96% 433M/449M [00:04<00:00, 124MB/s]
100% 449M/449M [00:04<00:00, 108MB/s]


In [9]:
import os, zipfile
try:
  os.mkdir("/content/data/")
except:
  print("data folder allready exists")

In [10]:
import os, zipfile

dir_name = "/content/"
target_dir = "/content/data/"
extension = ".zip"
 
os.chdir(dir_name) # change directory from working dir to dir with files

for item in os.listdir(dir_name): # loop through items in dir
    if item.endswith(extension): # check for ".zip" extension
        file_name = os.path.abspath(item) # get full path of files
        zip_ref = zipfile.ZipFile(file_name) # create zipfile object
        zip_ref.extractall(target_dir) # extract file to dir
        zip_ref.close() # close file
        os.remove(file_name) # delete zipped file

In [11]:
os.mknod("/content/heart_murmurs/__init__.py")

In [12]:
def replace_line(file_name, line_num, text):
    lines = open(file_name, 'r').readlines()
    lines[line_num] = text
    out = open(file_name, 'w')
    out.writelines(lines)
    out.close()

In [19]:
replace_line('/content/heart_murmurs/run_model.py',12,"from .helper_code import * \n")
replace_line('/content/heart_murmurs/run_model.py',13,"from .team_code import load_challenge_model, run_challenge_model \n")
replace_line('/content/heart_murmurs/cross_validate.py',14,"from .helper_code import * \n")
replace_line('/content/heart_murmurs/evaluate_model.py',16,"from .helper_code import load_patient_data, get_murmur, get_outcome, load_challenge_outputs, compare_strings \n")
replace_line('/content/heart_murmurs/team_code.py',11,"from .helper_code import * \n")
replace_line('/content/heart_murmurs/train_model.py',11,"from .helper_code import is_integer \n")
replace_line('/content/heart_murmurs/train_model.py',12,"from .team_code import train_challenge_model \n")


In [20]:
%load_ext autoreload
%autoreload
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [21]:
from heart_murmurs.helper_code import *

# have to add a "." in from of the module imports (in the scrips:train_model, run_model and team_code )
from heart_murmurs.train_model import *
from heart_murmurs.run_model import *
from heart_murmurs.team_code import *
from heart_murmurs.evaluate_model import *
from heart_murmurs.cross_validate import *

In [22]:
try:
  os.mkdir("/content/models/")
except:
  print("model folder allreadu exists")

In [23]:
try:
  os.mkdir("/content/results/")
except:
  print("results folder allreadu exists")

In [ ]:
murmur_model, clinical_model, murmur_probas, outcome_probas, murmur_trues, outcome_trues, murmur_history, clinical_history, val_data = cv_challenge_model(data_folder="/content/data/training_data/training_data/", result_folder="/content/results/", n_epochs_1=5,n_epochs_2=5, n_folds=3)

Finding data files...
Extracting features and labels from the Challenge data...


  0%|          | 0/942 [00:00<?, ?it/s]/content/heart_murmurs/cross_validate.py:90: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(current_recordings)[indx]
 72%|███████▏  | 675/942 [00:21<00:06, 41.52it/s]

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

def grad_cam(layer_name, data, model):
    grad_model = tf.keras.models.Model(
    [model.inputs], [model.get_layer(layer_name).output, model.output]
)
    last_conv_layer_output, preds = grad_model(data)

    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(data)
        pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]
    
    grads = tape.gradient(class_channel, last_conv_layer_output)


    pooled_grads = tf.reduce_mean(grads, axis=(0))

    last_conv_layer_output = last_conv_layer_output[0]

    heatmap = last_conv_layer_output * pooled_grads
    heatmap = tf.reduce_mean(heatmap, axis=(1))
    heatmap = np.expand_dims(heatmap,0)
    return heatmap

In [ ]:
"""
model = ...    
layer_name = "<last conv layer name>"
    
for example in X_test:
    exp = grad_cam("last_conv", np.expand_dims(example,0), model)
    plt.imshow(exp,cmap='Reds', aspect="auto", interpolation='nearest',extent=[0,5000,round(example.min()*1.05),round(example.max()*1.05)],
           vmin=exp.min(), vmax=exp.max(), alpha=1.0)
    plt.plot(example[:,1],'k') #plot lead II
    plt.colorbar()
    plt.show()
"""

In [ ]:
train_challenge_model("/content/data/training_data/training_data/", "/content/models/", 1)

Finding data files...
Extracting features and labels from the Challenge data...


  0%|          | 0/942 [00:00<?, ?it/s]/content/heart_murmurs/team_code.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(current_recordings)[indx]
100%|██████████| 942/942 [00:23<00:00, 39.57it/s]


Number of signals = 942
Murmurs prevalence:
Present = 179, Unknown = 68, Absent = 695
Outcomes prevalence:
Abnormal = 456, Normal = 486
Epoch 1/25
48/48 [==============================] - 57s 867ms/step - loss: 0.7385 - lr: 0.0010
Epoch 2/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6857 - lr: 0.0010
Epoch 3/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6660 - lr: 0.0010
Epoch 4/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6545 - lr: 0.0010
Epoch 5/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6514 - lr: 0.0010
Epoch 6/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6438 - lr: 0.0010
Epoch 7/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6183 - lr: 0.0010
Epoch 8/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6270 - lr: 0.0010
Epoch 9/25
48/48 [==============================] - 42s 865ms/step - loss: 0.6084 - lr: 0.0010
Epoch 10/

In [ ]:
try:
  os.mkdir("/content/output/")
except:
  print("output folder allready exist..")

output folder allready exist..


In [ ]:
run_model("/content/models/", "/content/data/training_data/training_data/", "/content/output/", allow_failures=True, verbose=1)

Loading Challenge model...
Running model on Challenge data...
[array([-425, 1045,  518, ...,  509,  443,  122], dtype=int16), array([2593, 1874, 1370, ..., -637, -255, -243], dtype=int16), array([ 2276,  2343,  2448, ..., -2732, -5634, -4290], dtype=int16), array([12672, 10041,  3215, ...,  -658,     8,   528], dtype=int16)]
Preprocessing test data...


/content/heart_murmurs/team_code.py:208: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  extracted_recordings = np.asarray(recordings)[indx]


Running model...
[[0.1011893  0.00937135 0.8894393 ]]
[[0.5203316]]
[array([1653, 3815, 3101, ...,  187,  348,   53], dtype=int16), array([32596, 28290,  8851, ...,  6449,  6299,  7167], dtype=int16), array([   244,  -3588, -22579, ...,   -207,   -205,   -204], dtype=int16), array([5039, 5952, 5754, ...,  344,  229,   87], dtype=int16)]
Preprocessing test data...
Running model...
[[9.7517526e-01 7.0674737e-06 2.4817649e-02]]
[[0.02909494]]
[array([  935,  1366,  1967, ..., -1857, -2410, -1732], dtype=int16), array([ 3528, -3508, -7229, ..., -1104, -1378, -1548], dtype=int16), array([ 869,  614,  687, ...,  712, 1431,  845], dtype=int16), array([-769, -813, -130, ..., -561, -124,   45], dtype=int16)]
Preprocessing test data...
Running model...
[[0.3974643  0.21054041 0.39199528]]
[[0.31984133]]
[array([   0,   33,  302, ..., -357,  -76,  513], dtype=int16), array([20835, 17880,  5868, ...,   -18,   -27,   -97], dtype=int16), array([ -74,  322,  192, ...,  263,  -32, -290], dtype=int16),

In [ ]:
evaluate_model("/content/data/training_data/training_data/", "/content/output/")

((['Present', 'Unknown', 'Absent'],
  0.5,
  0.3333333333333333,
  array([0.5, 0.5, 0.5]),
  array([0.19002123, 0.07218684, 0.73779193]),
  0.1064525721082367,
  array([0.31935772, 0.        , 0.        ]),
  0.19002123142250532,
  array([1., 0., 0.]),
  0.49888517279821626,
  14850.764331210192),
 (['Abnormal', 'Normal'],
  0.5,
  0.5,
  array([0.5, 0.5]),
  array([0.48407643, 0.51592357]),
  0.3261802575107296,
  array([0.65236052, 0.        ]),
  0.4840764331210191,
  array([1., 0.]),
  0.824295010845987,
  14850.764331210192))

CV