In [1]:
import tensorflow as tf
import os

In [2]:
model = tf.keras.models.load_model(os.path.join("./modelv2/" 'model.h5'))

AttributeError: 'CategoricalCrossentropy' object has no attribute '__name__'

In [8]:
model = tf.keras.models.load_model(os.path.join("./models/" 'model.h5'))

In [15]:
model.get_config()['layers'][0]['config']['batch_input_shape'][1]

500

In [2]:
from helper_code import *

In [3]:
path = "./data/dataset/training_data/"

In [4]:
patient_data = load_patient_data(path + "2530.txt")

In [5]:
patient_data

'2530 4 4000\nAV 2530_AV.hea 2530_AV.wav 2530_AV.tsv\nPV 2530_PV.hea 2530_PV.wav 2530_PV.tsv\nTV 2530_TV.hea 2530_TV.wav 2530_TV.tsv\nMV 2530_MV.hea 2530_MV.wav 2530_MV.tsv\n#Age: Child\n#Sex: Female\n#Height: 98.0\n#Weight: 15.9\n#Pregnancy status: False\n#Murmur: Absent\n#Murmur locations: nan\n#Most audible location: nan\n#Systolic murmur timing: nan\n#Systolic murmur shape: nan\n#Systolic murmur grading: nan\n#Systolic murmur pitch: nan\n#Systolic murmur quality: nan\n#Diastolic murmur timing: nan\n#Diastolic murmur shape: nan\n#Diastolic murmur grading: nan\n#Diastolic murmur pitch: nan\n#Diastolic murmur quality: nan\n#Campaign: CC2015\n#Additional ID: nan'

In [11]:
get_frequency(patient_data)

4000.0

In [9]:
recordings = load_recordings(path, patient_data)

In [10]:
recordings

[array([-425, 1045,  518, ...,  509,  443,  122], dtype=int16),
 array([2593, 1874, 1370, ..., -637, -255, -243], dtype=int16),
 array([ 2276,  2343,  2448, ..., -2732, -5634, -4290], dtype=int16),
 array([12672, 10041,  3215, ...,  -658,     8,   528], dtype=int16)]

In [ ]:
patient_data